if "monitor" == "left":
    oof = [
        widget.Sep(
            linewidth=0,
            padding=6,
            foreground=self.colors[2],
            background=self.colors[0]
        ),
        widget.Image(
            filename="~/.config/qtile/icons/python-white.png",
            scale="False",
            mouse_callbacks={'Button1': lambda: qtile.cmd_spawn(self.tilix)}
        ),
        widget.Sep(
            linewidth=0,
            padding=6,
            foreground=self.colors[2],
            background=self.colors[0]
        ),
        widget.GroupBox(
            font="Ubuntu Bold",
            fontsize=9,
            margin_y=3,
            margin_x=0,
            padding_y=5,
            padding_x=3,
            borderwidth=3,
            active=self.colors[2],
            inactive=self.colors[7],
            rounded=False,
            highlight_color=self.colors[1],
            highlight_method="line",
            this_current_screen_border=self.colors[6],
            this_screen_border=self.colors[4],
            other_current_screen_border=self.colors[6],
            other_screen_border=self.colors[4],
            foreground=self.colors[2],
            background=self.colors[0]
        ),
        widget.Prompt(
            prompt="Oofer: ",
            font="Ubuntu Mono",
            padding=10,
            foreground=self.colors[3],
            background=self.colors[1]
        ),
        widget.Sep(
            linewidth=0,
            padding=40,
            foreground=self.colors[2],
            background=self.colors[0]
        ),
        widget.WindowName(
            foreground=self.colors[6],
            background=self.colors[0],
            padding=0
        ),
        widget.Systray(
            background=self.colors[0],
            padding=5
        ),
        widget.Sep(
            linewidth=0,
            padding=6,
            foreground=self.colors[0],
            background=self.colors[0]
        ),
        widget.TextBox(
            text='',
            background=self.colors[0],
            foreground=self.colors[4],
            padding=0,
            fontsize=37
        ),
        widget.Net(
            interface="enp6s0",
            format='{down} ↓↑ {up}',
            foreground=self.colors[2],
            background=self.colors[4],
            padding=5
        ),
        widget.TextBox(
            text='',
            background=self.colors[4],
            foreground=self.colors[5],
            padding=0,
            fontsize=37
        ),
        widget.TextBox(
            text=" 🌡 TEMP NOT SHOWN ",
            padding=2,
            foreground=self.colors[2],
            background=self.colors[5],
            fontsize=11
        ),
        widget.ThermalSensor(
            foreground=self.colors[2],
            background=self.colors[5],
            threshold=90,
            padding=5
        ),
        widget.TextBox(
            text='',
            background=self.colors[5],
            foreground=self.colors[4],
            padding=0,
            fontsize=37
        ),
        widget.TextBox(
            text=" ⟳",
            padding=2,
            foreground=self.colors[2],
            background=self.colors[4],
            fontsize=14
        ),
        widget.CheckUpdates(
            update_interval=1800,
            distro="Arch_checkupdates",
            display_format="{updates} Updates",
            foreground=self.colors[2],
            mouse_callbacks={'Button1': lambda: qtile.cmd_spawn(self.tilix + ' -e sudo pacman -Syu')},
            background=self.colors[4]
        ),
        widget.TextBox(
            text='',
            background=self.colors[4],
            foreground=self.colors[5],
            padding=0,
            fontsize=37
        ),
        widget.TextBox(
            text=" 🖬",
            foreground=self.colors[2],
            background=self.colors[5],
            padding=0,
            fontsize=14
        ),
        widget.Memory(
            foreground=self.colors[2],
            background=self.colors[5],
            mouse_callbacks={'Button1': lambda: qtile.cmd_spawn(self.tilix + ' -e htop')},
            padding=5
        ),
        widget.TextBox(
            text='',
            background=self.colors[5],
            foreground=self.colors[4],
            padding=0,
            fontsize=37
        ),
        widget.TextBox(
            text=" ₿",
            padding=0,
            foreground=self.colors[2],
            background=self.colors[4],
            fontsize=12
        ),
        widget.BitcoinTicker(
            foreground=self.colors[2],
            background=self.colors[4],
            padding=5
        ),
        widget.TextBox(
            text='',
            background=self.colors[4],
            foreground=self.colors[5],
            padding=0,
            fontsize=37
        ),
        widget.TextBox(
            text=" Vol:",
            foreground=self.colors[2],
            background=self.colors[5],
            padding=0
        ),
        widget.Volume(
            foreground=self.colors[2],
            background=self.colors[5],
            padding=5
        ),
        widget.TextBox(
            text='',
            background=self.colors[5],
            foreground=self.colors[4],
            padding=0,
            fontsize=37
        ),
        widget.CurrentLayoutIcon(
            custom_icon_paths=[os.path.expanduser("~/.config/qtile/icons")],
            foreground=self.colors[0],
            background=self.colors[4],
            padding=0,
            scale=0.7
        ),
        widget.CurrentLayout(
            foreground=self.colors[2],
            background=self.colors[4],
            padding=5
        ),
        widget.TextBox(
            text='',
            background=self.colors[4],
            foreground=self.colors[5],
            padding=0,
            fontsize=37
        ),
        widget.Clock(
            foreground=self.colors[2],
            background=self.colors[5],
            format="%A, %B %d - %H:%M "
        ),
    ]
