#+TITLE: Polybar Config
#+PROPERTY: header-args :tangle config
#+STARTUP: showeverything
#+AUTHOR: Steve Tautonico

* Table Of Contents :toc:
- [[#basic-settings][Basic Settings]]
  - [[#colors][Colors]]
  - [[#global--window-manager][Global / Window Manager]]
- [[#bar][Bar]]
  - [[#common][Common]]
  - [[#left][Left]]
  - [[#right][Right]]
- [[#modules][Modules]]
  - [[#filesystem][Filesystem]]
  - [[#i3][I3]]
  - [[#cpu][CPU]]
  - [[#memory][Memory]]
  - [[#datetime][Datetime]]
  - [[#temperature][Temperature]]

* Basic Settings
Some basic settings applied globally across all of polybar and all bars

** Colors
Some color settings that are applied globally across all bars

#+begin_src ini :tangle config
[colors]
background = #222
background-alt = #444

foreground = #dfdfdf
foreground-alt = #555

primary = #2974FF
secondary = #e60053
alert = #bd2c40
#+end_src

** Global / Window Manager
These settings are "general purpose" global settings and settings specific to the window manager

#+begin_src ini :tangle config
; Global settings
[settings]
screenchange-reload = true

[global/wm]
margin-top = 5
margin-bottom = 5
#+end_src


* Bar
A bar is the "bar" on the top of the screen. A bar can be configured with modules that add components and functionality to the bar.

** Common
The "common" bar isn't actually displayed on screen, but is used for "shared" settings.
The "actual" bars inherit the settings from the common bar.
This is used so common settings don't have to be re-defined on both bars (dual monitor setup)

#+begin_src ini :tangle config
[bar/common]
width = 100%
height = 27
radius = 6.0
fixed-center = false

; Colors
background = ${colors.background}
foregroud = ${colors.foreground}

line-size = 2
line-color = #f00

border-size = 4
border-color = #00000000

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = fixed:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = siji:pixelsize=10;1
font-3 = Font Awesome 6 Free:pixelsize=12;2
font-4 = Font Awesome 6 Free Solid:pixelsize=12;2
font-5 = Font Awesome 6 Brands:pixelsize=12;2

; No tray by default, we assign it to a specific monitor
tray-position = none
tray-padding = 2
;tray-background = #0063ff

scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev

cursor-click = pointer
cursor-scroll = ns-resize
#+end_src
** Left
The bar for the left monitor (DP-2).
This bar contains the following modules:
- [[I3][i3]]
- [[Filesystem][filesystem]]
- [[Memory][memory]]
- [[CPU][cpu]]
- [[Temperature][temperature]]
- [[Datetime][datetime]]

#+begin_src ini :tangle config
[bar/left]
inherit = bar/common

monitor = DP-2

modules-left = i3
modules-center =
modules-right = filesystem memory cpu temperature datetime
#+end_src

** Right
The bar for the right monitor (HDMI-0).
This bar contains the following modules:
- [[I3][i3]]
- [[Filesystem][filesystem]]
- [[Memory][memory]]
- [[CPU][cpu]]
- [[Temperature][temperature]]
- [[Datetime][datetime]]

This bar also contains the system tray. Its on the right monitor instead because it overlays on full screen applications.
Since the right monitor usually doesn't have fullscreen apps, its better to have it there.

#+begin_src ini :tangle config
[bar/right]
inherit = bar/common

monitor = HDMI-0

modules-left = i3
modules-center =
modules-right = filesystem memory cpu temperature datetime

tray-position = right
#+end_src

* Modules
Modules are individual components that sit on a bar. These components may or may not be interactive.

** Filesystem
The /filesystem/ component displays the amount of storage used in a given disk/folder.
This specific component displays the percent of storage used in the "/" folder.

#+begin_src ini :tangle config
[module/filesystem]
type = internal/fs
interval = 30
mount-0 = /

label-mounted = %{F#0a81f5}%mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}
#+end_src

** I3
The /i3/ module allows polybar to interact with the window manager (i3 in this case).
It displays the workspaces on the current monitor.
It also sets custom icons for the "special" workspaces (like discord, steam, etc)

#+begin_src ini :tangle config
[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
pin-workspaces = true

; Workspace icons
ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = 10;10

; Special workspaces
ws-icon-10 = 11;
ws-icon-11 = 12;
ws-icon-12 = 13;
ws-icon-13 = 14;
ws-icon-14 = 15;

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %icon%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %icon%
label-unfocused-padding = 2

; visible = Active workspace on unfocused monitor
label-visible = %icon%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

; Separator in between workspaces
; label-separator = |
#+end_src

** CPU
The /cpu/ module shows the load on the CPU or CPU cores.
This specific example shows the overall CPU load (percentage) and a small bar showing the load for each core.

#+begin_src ini :tangle config
[module/cpu]
type = internal/cpu
interval = 2
format = <label> <ramp-coreload>
format-prefix = " "
format-prefix-foreground = #f90000
format-underline = #f90000
label = %percentage:2%%

ramp-coreload-spacing = 1
ramp-coreload-0 = ▁
ramp-coreload-1 = ▂
ramp-coreload-2 = ▃
ramp-coreload-3 = ▄
ramp-coreload-4 = ▅
ramp-coreload-5 = ▆
ramp-coreload-6 = ▇
ramp-coreload-7 = █
#+end_src

** Memory
The /memory/ module is very similar to the /cpu/ module, except it shows the RAM load.
This specific example shows the percentage of the RAM load.

#+begin_src ini :tangle config
[module/memory]
type = internal/memory
interval = 2
; This shows as a safari icon but its definitly not (ram icon)
format-prefix = " "
format-prefix-foreground = #4bffdc
format-underline = #4bffdc
label = %percentage_used%%
#+end_src

** Datetime
The /datetime/ module can be configured to show different time/date configurations in any format you want.
The date and time format are configured using the [[https://en.cppreference.com/w/cpp/io/manip/put_time][C++ std::put_time format string parameters]]
This specific example is configured to show: [ HOUR:MINUTE:SECOND | DAY, MONTH DATE ]

#+begin_src ini :tangle config
[module/datetime]
type = internal/date
interval = 1

date = %a, %b %d
time = %I:%M:%S

date-alt = %a, %b %d
time-alt = %I:%M:%S %p

label = [ %time% | %date% ]
#+end_src

** Temperature
The /temperature/ module displays the current CPU temperature (in degrees C)

#+begin_src ini :tangle config
[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}
#+end_src
