#+TITLE: i3 Config
#+PROPERTY: header-args :tangle config
#+OPTIONS: toc:3
#+STARTUP: showeverything
#+AUTHOR: Steve Tautonico

* Table of Contents :toc:
- [[#basic-settings][Basic Settings]]
- [[#workspaces][Workspaces]]
- [[#keybinds][Keybinds]]
  - [[#common-programs][Common Programs]]
  - [[#navigation-and-control][Navigation and Control]]
  - [[#modes][Modes]]
- [[#bar--autostart][Bar + Autostart]]

* Basic Settings
These settings are the most basic settings throughout the entire config.
These lines set:
- The main modifier button (win/super button)
- Configure i3-gaps
- Disable window title
- Set the font

#+begin_src i3 :tangle config
# vim: filetype=i3config

# Set the modifier key to the Super/Win key
set $mod Mod4

# Set the floating draw/resize modifier key to Super/Win
floating_modifier $mod

# Configure gaps
gaps inner 6
gaps outer 0
smart_gaps on

# Disable focus border + window title
default_border pixel 0
for_window [class="^.*"] border pixel 0

# Font used for window titles
font pango:DejaVu Sans Mono 10
#+end_src


* Workspaces
There are 5 general purpose workspaces per monitor * 2 monitor = 10 gp workspaces.
There are also 5 application specific workspaces:
- Discord
- Steam
- Signal
- Zoom
- Spotify

Whenever one of these specific apps are opened, they are automatically placed on their specific workspaces

Some programs are set to float by default. Some of these windows include: download prompts, notifications,
auto-fill on programs like pycharm, etc...

Note: The "special" workspaces are locked to the right monitor becuase I can't figure out how to use them on either/both

#+begin_src i3 :tangle config
# Automatic floating windows for specific classes
for_window [class="confirm"] floating enable
for_window [class="dialog"] floating enable
for_window [class="download"] floating enable
for_window [class="error"] floating enable
for_window [class="file_progress"] floating enable
for_window [class="notification"] floating enable
for_window [class="splash"] floating enable
for_window [class="toolbar"] floating enable
for_window [class="xephyr"] floating enable
for_window [class="Xephyr"] floating enable
for_window [class="confirmreset"] floating enable
for_window [class="maketag"] floating enable
for_window [class="makebranch"] floating enable
for_window [class="branchdialog"] floating enable
for_window [class="pinentry"] floating enable
for_window [class="ssh-askpass"] floating enable

# Bind specific windows to specific workspaces
assign [class="^discord$"] $discordws
assign [class="Steam"] $steamws
assign [class="Signal"] $signalws
assign [class="^zoom$"] $zoomws
# This doesn't work for some reason
assign [class="^Spotify*"] $spotifyws
# But this does (TODO: Investigate and fix)
for_window [class="Spotify"] move to workspace $spotifyws
# include ./workspaces

# Monitor names
set $monitorLeft "DP-4"
set $monitorRight "HDMI-0"

# Workspace Names
set $ws1 1
set $ws2 2
set $ws3 3
set $ws4 4
set $ws5 5
set $ws6 6
set $ws7 7
set $ws8 8
set $ws9 9
set $ws10 10

set $discordws 11
set $steamws 12
set $signalws 13
set $zoomws 14
set $spotifyws 15

# Bind workstations to specific monitors
workspace $ws1 output $monitorLeft
workspace $ws2 output $monitorLeft
workspace $ws3 output $monitorLeft
workspace $ws4 output $monitorLeft
workspace $ws5 output $monitorLeft

workspace $ws6 output $monitorRight
workspace $ws7 output $monitorRight
workspace $ws8 output $monitorRight
workspace $ws9 output $monitorRight
workspace $ws10 output $monitorRight

# Bind Special workspaces to specific monitors until I can figure out how to make them work on both
# monitors
workspace $discordws output $monitorRight
workspace $steamws output $monitorRight
workspace $signalws output $monitorRight
workspace $zoomws output $monitorRight
workspace $spotifyws output $monitorRight
#+end_src


* Keybinds
The keybinds are the basis of i3. They allow the desktop to be controlled.
They are split into a few sub-sections:

** Common Programs
These bindings are for launching commonly used programs.

| Binding           | Opens                     |
|-------------------+---------------------------|
| Super + T         | Alacritty (Terminal)      |
| Super + E         | Ranger (File Manager)     |
| Super + F         | Firefox Developer Edition |
| Super + Shift + S | Screenshot With Flameshot |
| Super + D         | Doom Emacs                |

#+begin_src i3 :tangle config
# Terminal
bindsym $mod+t exec /usr/bin/alacritty

# File manager (ranger)
# bindsym $mod+e exec /usr/bin/alacritty -e /usr/bin/ranger
bindsym $mod+e exec /usr/bin/xranger

# Firefox
bindsym $mod+f exec /usr/bin/firefox-developer-edition

# Screnshot with flameshot
bindsym $mod+Shift+s exec /usr/bin/flameshot gui

# Open emacs (d for doom)
bindsym $mod+d exec /usr/bin/emacsclient -c -a "emacs"
#+end_src

** Navigation and Control
These keybinds are for navigating around the desktop, moving containers, and other desktop control settings.

| Binding             | Description                               |
|---------------------+-------------------------------------------|
| Super + W           | Close the current window                  |
| Super + 1-0         | Switch to workspace 1-10                  |
| Super + Shift + 1-0 | Move the current window to workspace 1-10 |
| Super + H           | Move focus left                           |
| Super + J           | Move focus down                           |
| Super + K           | Move focus up                             |
| Super + L           | Move focus right                          |
| Super + Shift + H   | Move current container left               |
| Super + Shift + J   | Move current container down               |
| Super + Shift + K   | Move current container up                 |
| Super + Shift + L   | Move current container right              |
| Super + Control + H | Split to horizontal view                  |
| Super + Control + V | Split to vertical view                    |
| Super + Control + Q | Change layout to split view               |
| Super + Control + W | Change layout to tabbed view              |
| Super + Shift + F   | Toggle floating mode on current window    |
| Super + Control + F | Toggle full-screen mode on current window |
| Super + Shift + C   | Reload the config file                    |
| Super + Shift + R   | Restart i3                                |
| Super + Control + L | Lock the desktop using fancylock          |
| Super + Shift + E   | Open the logout prompt (exit i3)          |

#+begin_src i3 :tangle config
# Close a window
bindsym $mod+w kill

# Switch workspaces
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

# Special workspaces
#bindsym $mod+Control+d workspace number $discordws
#bindsym $mod+Control+z workspace number $zoomws

# Move a special container to a workspace
bindsym $mod+Control+Shift+d move container to workspace number $wsdiscord
bindsym $mod+Control+Shift+z move container to workspace number $zoomws

# Move the focused container to a specific workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

# Change focus (h,j,k,l)
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# Shift the focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# Split to horizonal view
bindsym $mod+Control+h split h

# Split to vertical view
bindsym $mod+Control+v split v

# Change layout (split, tabbed)
bindsym $mod+Control+q layout toggle split
bindsym $mod+Control+w layout tabbed

# Toggle a window floating
bindsym $mod+Shift+f floating toggle

# Make a window fullscreen
bindsym $mod+Control+f fullscreen toggle

# Reload the config file
bindsym $mod+Shift+c reload

# Restart i3 (keeps layout/session)
bindsym $mod+Shift+r restart

# Lock the desktop (using the custom fancylock script)
bindsym $mod+Control+l exec $HOME/.config/i3/fancylock/lock --blur=0x16 --no-text

# Logout of I3
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
#+end_src

** Modes
These modes are sub-layers of characters that bind simpler bindings to tasks.

*** Resize
Resize mode allows for the current focused window to be resized.
Each time a direction is pressed, the current window is resized by 10 units in the given direction

| Binding   | Description             |
|-----------+-------------------------|
| Super + R | En/Dis-able resize mode |
| H         | Decrease width          |
| J         | Increase height         |
| K         | Decrease height         |
| L         | Increase width          |
| Escape    | Disable resize mode     |
| Enter     | Disable resize mode     |

#+begin_src i3 :tangle config
# Resize mode (Reize with h,j,k,l and exit using Enter, Escape, or Super+r again
mode "resize" {
    bindsym h resize shrink width 10 px or 10 ppt
    bindsym j resize grow height 10 px or 10 ppt
    bindsym k resize shrink height 10 px or 10 ppt
    bindsym l resize grow width 10 px or 10 ppt

    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+r mode "default"
}
# Enter/Exit resize mode
bindsym $mod+r mode "resize"
#+end_src

*** Special WS
Special WS mode allows movement to and from "special" workspaces (ones bound to apps like steam, discord, etc)

Note: WS = workspace

| Binding             | Description                               |
|---------------------+-------------------------------------------|
| Super + Control + S | En/Dis-able special WS mode               |
| D                   | Switch to discord WS                      |
| Shift + D           | Move the focused window to discord WS     |
| S                   | Switch to steam WS                        |
| Shift + S           | Move the focused window to steam WS       |
| G                   | Switch to signal WS                       |
| Shift + G           | Move the focused window to the signal WS  |
| P                   | Switch to spotify WS                      |
| Shift + P           | Move the focused window to the spotify WS |
| Escape              | Disable special ws mode                   |
| Enter               | Disable special ws mode                   |

#+begin_src i3 :tangle config
# Special WS mode allows movment to and from special workspaces
mode "special WS" {
    # Discord
    bindsym d workspace number $discordws; mode "default"
    bindsym Shift+d move container to workspace number $discordws

    # Steam
    bindsym s workspace number $steamws; mode "default"
    bindsym Shift+s move container to workspace number $steamws

    # Signal
    bindsym g workspace number $signalws; mode "default"
    bindsym Shift+g move container to workspace number $signalws

    # Zoom
    bindsym z workspace number $zoomws; mode "default"
    bindsym Shift+z move container to workspace number $zoomws

    # Spotify
    bindsym p workspace number $spotifyws; mode "default"
    bindsym Shift+p move container to workspace number $spotifyws

    # Exit to normal mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+Control+s mode "default"
}

bindsym $mod+Control+s mode "special WS"
#+end_src

*** Config
Config mode opens some common config in emacs (or $VISUAL)

| Binding             | Config                  |
|---------------------+-------------------------|
| Super + Control + C | En/Dis-able config mode |
| I                   | i3 config               |
| A                   | alacritty.yml           |
| D                   | dunstrc                 |
| P                   | picom.conf              |
| Y                   | polybar config          |
| H                   | polybar modules         |
| Escape              | Disable config mode     |
| Enter               | Disable config mode     |

#+begin_src i3 :tangle config
# Edit mode allows quick opening of common config files
mode "config" {
    # i3 Config
    bindsym i exec "/usr/bin/emacsclient -c $HOME/.config/i3/config"; mode "default"

    bindsym a exec "/usr/bin/emacsclient -c $HOME/.config/alacritty/alacritty.yml"; mode "default"

    bindsym d exec "/usr/bin/emacsclient -c $HOME/.config/dunst/dunstrc"; mode "default"

    bindsym p exec "/usr/bin/emacsclient -c $HOME/.config/picom/picom.conf"; mode "default"

    # Polybar config
    bindsym y exec "/usr/bin/emacsclient -c $HOME/.config/polybar/config"; mode "default"
    bindsym h exec "/usr/bin/emacsclient -c $HOME/.config/polybar/modules"; mode "default"

    # Exit to normal mode
    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+Control+c mode "default"
}

bindsym $mod+Control+c mode "config"
#+end_src

* Bar + Autostart
This configuration uses Polybar as its main bar.
i3status is also enabled but not used.

All the programs that run when i3 starts up are in the "autostart.sh"

#+begin_src i3 :tangle config
# Enable i3status and polybar
bar {
    status_command i3status
    i3bar_command $HOME/.config/polybar/launch.sh
}

# Autostart programs
exec_always --no-startup-id $HOME/.config/i3/autostart.sh
#+end_src

autostart.sh

#+begin_src shell :tangle autostart.sh
#!/bin/sh
function run {
    if ! pgrep $1 > /dev/null ;
    then
        $@&
    fi
}

# Autostart programs
#run picom --experimental-backend &
run picom -b -c -C -G &
run nitrogen --restore &
# run xfce4-clipman
run /usr/bin/discord-canary

# Set proper video mode
xrandr --output HDMI-0 --mode 2560x1440 --rate 144.00 --right-of DP-2
xrandr --output DP-2 --primary --mode 2560x1440 --rate 144.00 --left-of HDMI-0

run dunst

# Enable numlock on start
numlockx on

# Set the button repeat rate
xset r rate 300 50

# Set mouse sensitiviy
xinput --set-prop 9 'libinput Accel Speed' -0.5

# Update Kensington Expert settings
/home/steve/Documents/Scripts/Kensington_Expert_Setup.sh

systemctl --user start ulauncher

/home/steve/.config/polybar/launch.sh

emacs --daemon
#+end_src
